remote_theme: pages-themes/cayman@v0.2.0

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title: Missão Catálica Portuguesa de Londres
description: Missão Catálica Portuguesa de Londres

show_downloads: false
google_analytics: ""
