theme: jekyll-theme-cayman

#remote_theme: pages-themes/cayman@v0.2.0

#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one


title: Miss찾o Cat처lica Portuguesa em Londres
description: Miss찾o Cat처lica Portuguesa em Londres

show_downloads: false
github: false

google_analytics:

plugins:
 - jekyll-feed
 - jekyll-seo-tag
